on:
 push:
    branches: [ master ]
name: Angular Build
jobs:
  checkVersion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check if version has been updated
      id: check
      uses: EndBug/version-check@v1

    - name: Log when changed
      if: steps.check.outputs.changed == 'true'
      run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

    - name: Log when unchanged
      if: steps.check.outputs.changed != 'true'
      run: 'echo "No version change"'

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run:  npm ci

      - name: npm run build
        run: npm run build:prod
